### ISSUE TITLE
Issue with loadmch.m

### ISSUE THREAD

**Issue by Gianno91** [fangq/mmc#8] opened 2018-03-09 14:57 UTC
I recently run a simulation using 30 million photons on a domain of my creation, which is composed of 12 regions and includes a 2D planar source and a point detector. Running the simulation with -x 1 gave me a .mch result file with the detected photons' info. 

However, when I tried to read the file using loadmch.m, I did not obtain the matrix that I expected, which should have dimensions N x M, such as N = number of detected photons, and M = 32 (since there are 12 regions in my domain). Instead, I got a N x 22 matrix that looks like a badly reshaped version of the correct matrix: the elements are not in the right positions.

I attached the MMC files I used to run the simulation in a .zip folder.
[MMC files.zip](https://github.com/fangq/mmc/files/1797285/MMC.files.zip)

Luca Giannoni

**Comment by fangq** [comment] 2018-03-11 19:19
@Gianno91, I tested your provided sample project using the latest mmc, I could not reproduce the issue.

loadmch() loaded the file correctly and returned an array 2999879 x 32, the values look fine to me. see log below:

```
fangq@taote:/drives/taote1/users/fangq/git/Project/mmc/examples/Luca$ matlab711 -nojvm
>> which loadmch
/home/users/fangq/space/git/Project/github/mcx/utils/loadmch.m
>> addpath('../../matlab/')
>> which loadmch           
/drives/taote1/users/fangq/git/Project/mmc/matlab/loadmch.m
>> [dat,header]=loadmch('Model_Results.mch');
>> header

header = 

           version: 1
          medianum: 12
            detnum: 1
         recordnum: 32
       totalphoton: 3000000
    detectedphoton: 2999879
       savedphoton: 2999879
        lengthunit: 1
          seedbyte: 0
        normalizer: 3.3327e+03

>> size(dat)

ans =

     2999879          32
>> dat(1:10,[1 2 3 13 14 end-7:end])

ans =

    1.0000  390.0000    9.0000  203.0000   42.5805   21.0053   -2.7173    0.8439    2.7500    0.1307   -0.3828    0.9145    1.0000
    1.0000  265.0000         0   25.0000   27.6814    2.2709    1.9054   -1.6514    2.7500   -0.0820   -0.8165    0.5714    1.0000
    1.0000   91.0000         0  159.0000   12.0848   18.7699    6.2720   -7.7569    2.7500   -0.1716    0.3594    0.9173    1.0000
    1.0000  294.0000         0         0   34.2439         0   10.0000   -3.5225    0.9203    0.8809    0.2112   -0.4235    1.0000
    1.0000   19.0000         0         0    3.0542         0    3.4934   -0.1504    2.7500   -0.3190   -0.5032    0.8032    1.0000
    1.0000  150.0000         0   24.0000   14.2894    2.1730  -10.0000   -3.4012   -2.5090   -0.9074    0.4121    0.0830    1.0000
    1.0000   64.0000         0         0    6.8099         0  -10.0000    0.6183    0.8330   -0.6307   -0.6180    0.4694    1.0000
    1.0000   14.0000         0         0    1.3038         0   10.0000    0.8013    2.1891    0.8246   -0.5587    0.0886    1.0000
    1.0000   89.0000         0   40.0000    9.4388    4.6678    4.1908  -10.0000   -2.2999    0.3298   -0.8992    0.2874    1.0000
    1.0000   21.0000         0         0    3.1845         0    9.5351   -1.8785    2.7500   -0.5458    0.1193    0.8293    1.0000
```

It is my suspicion that your matlab search path must have put the folder containing the old version of loadmch in the front of the new version. To verify, please type

`which loadmch
`
and see if this points to the correct path (if it points to the latest version of mcx/utils or mmc/matlab, this is ok, however, if it points to an older version of mcx or mmc, it will cause incorrect data reshaping).

Can you please verify the path of the loadmch? if you addpath to the latest mmc/matlab folder, will this issue appear again?

**Comment by yaoruoyang** [comment] 2018-03-11 19:26
That's my suspicion too : the loadmch file is not the latest version. We did made some modifications to the data structure of a detected photon within 1-2 years. Previously we only store the total scattering numbers of a photon, but now we are storing the scattering numbers for each different media type. If you are using the old loadmch that designed for the previous output format, that could generate some issues as you reported.

**Comment by Gianno91** [comment] 2018-03-12 10:56
Attached is the loadmch.m function I have been using so far;
[loadmch.zip](https://github.com/fangq/mmc/files/1802410/loadmch.zip)

Is it the correct version?

Luca

**Comment by Gianno91** [comment] 2018-03-12 13:16
I downloaded the most recent version of the loadmch.m function and now it reads the output .mch files correctly.

Many many thanks for your support.

Luca

**Comment by yaoruoyang** [comment] 2018-03-12 14:06
@fangq Hi Dr. Fang, I found that the description for this function is not updated yet, we need to change that before the new release.
https://github.com/fangq/mmc/blob/master/matlab/loadmch.m#L14

**Comment by fangq** [comment] 2018-05-03 18:34
the description was now updated in the following commit:

https://github.com/fangq/mmc/commit/993a5dfa7cf4f7f0f3c07ae2c7ce9c321ceed426#diff-d5b5fcdce4362c6f90ef55afa5466e3c

closing this issue now.

**Closed by fangq** 2018-05-03 18:34 UTC
