### ISSUE TITLE
Photon detection discrepancies between CPU and GPU run simulations

### ISSUE THREAD

**Issue by rajsinghmn** [fangq/mmc#69] opened 2021-05-13 22:01 UTC
Hey MMC team, 

I wrote a helper script that takes the detected photon output from a simulation and reconstructs the detector image based on photon exit locations. It seems to be working fine for detected outputs from single-threaded simulations (i.e. cfg.gpuid == -1) but not with opencl enabled simulations (i.e. cfg.gpuid == 1); fluence distributions look the same though. Any thoughts on how to get matching detected photon results for the accelerated simulations?

Thanks for your help!

**Comment by rajsinghmn** [comment] 2021-06-18 12:03
Bump

**Comment by fangq** [comment] 2021-06-18 14:34
sorry, did not see this thread until now. can you provide me a matlab script so I can reproduce the issue?

**Comment by fangq** [comment] 2021-08-18 22:01
re-reading this issue, I realized that the request is no possible - reproduced results can not be achieved when you change the parallel thread numbers, this is because additions are not associative: i.e. (p1+p2)+p3 is different from p1+(p2+p3), whcih happens when the parallel thread scheduler does not accumulate numbers in the same order

see

http://ic.ese.upenn.edu/pdf/parallel_fpaccum_tc2016.pdf

also, CPU and GPU hardware may impose additional differences, making matching the two results impossible.

closing this for now.

**Closed by fangq** 2021-08-18 22:01 UTC
